project:
  type: website
  output-dir: docs

website:
  title: "Mingyang"
  navbar:
    right:
      - icon: house-gear-fill
        text: Home
        href: 'https://mingyangluo906401072.github.io/'
      - icon: calendar2-week
        text: Blog
        href: 'https://mingyangluo906401072.github.io/blog'
      - icon: emoji-wink
        text: Handshake
        href: 'https://vt.joinhandshake.com/stu/users/29799250'
      - icon: linkedin
        text: LinkedIn
        href: 'https://linkedin.com'
      - icon: github
        text: Github
        href: 'https://github.com'
      - icon: envelope-at
        text: Email
        href: 'mailto:lmingyang@vt.edu'
format:
  html:
    theme: 
      light: yeti
      dark: slate
    css: styles.css

editor: visual

