project:
  type: website
  output-dir: docs

website:
  title: "Mingyang Blog"
  navbar:
    right:
      - icon: house
        text: Home
        href: 'https://mingyangluo906401072.github.io/'
      - icon: pencil
        text: Blog
        href: 'https://mingyangluo906401072.github.io/blog'
      - icon: twitter
        text: Twitter
        href: 'https://twitter.com'
      - icon: linkedin
        text: LinkedIn
        href: 'https://linkedin.com'
      - icon: github
        text: Github
        href: 'https://github.com'
format:
  html:
    theme: 
      light: yeti
      dark: slate
    css: styles.css

editor: visual

